### ISSUE TITLE
Multiple implementations are not resolved correctly

### ISSUE THREAD

**Issue by godrose** [SpecFlowOSS/BoDi#39]
This is a regression introduced in v1.5.0

Execute specs found at

https://github.com/godrose/Solid/tree/v2.3.0/Solid.IoC.Adapters.BoDi.Specs
They should work.
Then upgrade the BoDi version
Run again. Observe the failing test.

**Comment by godrose** [comment]
@gasparnagy @SabotageAndi 
This is a breaking change. I will look into it when I have time but first of all I'd like to understand whether this is by design.

**Comment by SabotageAndi** [comment]
FYI @tzongithub

**Comment by godrose** [comment]
@SabotageAndi Any update on this? For me it's a showstopper.
I won't be able to use any 3.7+ version

**Comment by SabotageAndi** [comment]
@tzongithub had a look at it. I can't remember the outcome anymore.

**Comment by SabotageAndi** [comment]
I just found it on our board for the sprint. We simply didn't get to this yet.

**Comment by tzongithub** [comment]
@godrose 
If I ugprade SpecFlow and BoDi in Solid and run the test I see the following error:
`FluentAssertions.Execution.AssertionFailedException
Expected type to be Solid.IoC.Adapters.BoDi.Specs.DependencyA, but found Solid.IoC.Adapters.BoDi.Specs.DependencyB.`

This is simply because the dependencies returned by ResolveAll do not have a guaranteed order. 
As your test assumes a fixed order (DepA, DepB) it might break:
```
        [Then(@"The services collection should be resolved by implementations")]
        public void ThenTheServicesCollectionShouldBeResolvedByImplementations()
        {
            var container = _scenarioContext.Get<IIocContainer>("container");
            var dependencies = container.ResolveAll<IDependency>().ToArray();
            dependencies[0].Should().BeOfType<DependencyA>();
            dependencies[1].Should().BeOfType<DependencyB>();
        }
```
I'd suggest to change the assertion in a way that it ignores the order.
E.g. this might work with fluent:
dependencies.Select(d => d.GetType()).Should().BeEquivalentTo(typeof(DependencyA), typeof(DependencyB));

**Comment by godrose** [comment]
@tzongithub Thanks. I will check
