### ISSUE TITLE
DisposeAsync support

### ISSUE THREAD

**Issue by roadz99** [SpecFlowOSS/BoDi#49]
Are there any plans to support IAsyncDisposable in this container?

**Comment by SabotageAndi** [comment]
No. We won't probably use it for a long time in SpecFlow.
But that doesn't mean, that we would not accept a PR for it

**Comment by idg10** [comment]
I know you closed this @SabotageAndi but since you said you might accept a PR, I've drafted a PR:

https://github.com/SpecFlowOSS/BoDi/pull/51

I wanted to use this to prototype an implementation of https://github.com/SpecFlowOSS/SpecFlow/issues/2575 - support in BoDi is a prerequisite for enabling `IAsyncDisposable` in SpecFlow. But it would be good to know whether this is a feature that's likely to get merged.

If you are interested in having `IAsyncDisposable` support in SpecFlow, I'll go ahead and prototype that out based on the BoDi implementation in #51, and once I'm confident that the BoDi side of things is able to support the SpecFlow feature, I'll change #51 from a draft PR to a real one.

But if this is something you're not likely to accept, please let me know and I'll stop now.
